// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

// Product defines model for Product.
type Product struct {
	Category *string `json:"category,omitempty"`
	Id       int64   `json:"id"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
}

// UpdateProductRequest defines model for UpdateProductRequest.
type UpdateProductRequest struct {
	Category *string  `json:"category,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Price    *float64 `json:"price,omitempty"`
}

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = UpdateProductRequest
