// Code generated by github.com/willabides/oapitesthandler/cmd/oapitesthandler. DO NOT EDIT.

package petstoretest

import (
	"bytes"
	"io"
	"net/http"

	externalRef0 "github.com/willabides/oapitesthandler/example/petstore/internal/common/oapi"
)

type TestHandler struct {
	tb TB

	handler http.Handler

	addPetExpectResponses                   expectResponses[AddPetRequestObject, AddPetResponseObject]
	updatePetExpectResponses                expectResponses[UpdatePetRequestObject, UpdatePetResponseObject]
	findPetsByStatusExpectResponses         expectResponses[FindPetsByStatusRequestObject, FindPetsByStatusResponseObject]
	findPetsByTagsExpectResponses           expectResponses[FindPetsByTagsRequestObject, FindPetsByTagsResponseObject]
	deletePetExpectResponses                expectResponses[DeletePetRequestObject, DeletePetResponseObject]
	getPetByIdExpectResponses               expectResponses[GetPetByIdRequestObject, GetPetByIdResponseObject]
	updatePetWithFormExpectResponses        expectResponses[UpdatePetWithFormRequestObject, UpdatePetWithFormResponseObject]
	getPetMetadataExpectResponses           expectResponses[GetPetMetadataRequestObject, GetPetMetadataResponseObject]
	getPetPhotoByIdExpectResponses          expectResponses[GetPetPhotoByIdRequestObject, GetPetPhotoByIdResponseObject]
	getPetRegistrationExpectResponses       expectResponses[GetPetRegistrationRequestObject, GetPetRegistrationResponseObject]
	uploadFileExpectResponses               expectResponses[UploadFileRequestObject, UploadFileResponseObject]
	getStoreInventoryExpectResponses        expectResponses[GetStoreInventoryRequestObject, GetStoreInventoryResponseObject]
	postStoreOrderExpectResponses           expectResponses[PostStoreOrderRequestObject, PostStoreOrderResponseObject]
	deleteOrderExpectResponses              expectResponses[DeleteOrderRequestObject, DeleteOrderResponseObject]
	getOrderByIdExpectResponses             expectResponses[GetOrderByIdRequestObject, GetOrderByIdResponseObject]
	createUserExpectResponses               expectResponses[CreateUserRequestObject, CreateUserResponseObject]
	createUsersWithListInputExpectResponses expectResponses[CreateUsersWithListInputRequestObject, CreateUsersWithListInputResponseObject]
	loginUserExpectResponses                expectResponses[LoginUserRequestObject, LoginUserResponseObject]
	logoutUserExpectResponses               expectResponses[LogoutUserRequestObject, LogoutUserResponseObject]
	deleteUserExpectResponses               expectResponses[DeleteUserRequestObject, DeleteUserResponseObject]
	getUserByNameExpectResponses            expectResponses[GetUserByNameRequestObject, GetUserByNameResponseObject]
	updateUserExpectResponses               expectResponses[UpdateUserRequestObject, UpdateUserResponseObject]
}

func (s *TestHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.handler.ServeHTTP(w, r)
}

func NewTestHandler(tb TB) *TestHandler {
	th := &TestHandler{tb: tb}
	s := &testServer{tb: tb, handler: th}
	th.handler = Handler(NewStrictHandler(s, nil))
	return th
}

type AddPetExpectation struct {
	handler *TestHandler
	req     AddPetRequestObject
	rawBody io.Reader
	opts    []ExpectOption
}

type addPetRawResponder struct {
	req AddPetRequestObject
	fn  func(AddPetRequestObject, http.ResponseWriter) error
}

func (r addPetRawResponder) VisitAddPetResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON201 sets the expectation to return a 201 response with JSON content.
func (b *AddPetExpectation) RespondJSON201(resp Pet) {
	typedResp := AddPet201JSONResponse(resp)
	b.handler.addPetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *AddPetExpectation) Respond400() {
	var resp AddPet400Response
	b.handler.addPetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Respond422 sets the expectation to return a 422 response.
func (b *AddPetExpectation) Respond422() {
	var resp AddPet422Response
	b.handler.addPetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *AddPetExpectation) Handle(fn func(AddPetRequestObject, http.ResponseWriter) error) {
	resp := addPetRawResponder{req: b.req, fn: fn}
	b.handler.addPetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

type UpdatePetExpectation struct {
	handler *TestHandler
	req     UpdatePetRequestObject
	rawBody io.Reader
	opts    []ExpectOption
}

type updatePetRawResponder struct {
	req UpdatePetRequestObject
	fn  func(UpdatePetRequestObject, http.ResponseWriter) error
}

func (r updatePetRawResponder) VisitUpdatePetResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *UpdatePetExpectation) RespondJSON200(resp Pet) {
	typedResp := UpdatePet200JSONResponse(resp)
	b.handler.updatePetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// RespondJSON400 sets the expectation to return a 400 response with JSON content.
func (b *UpdatePetExpectation) RespondJSON400(resp UpdatePet400JSONResponse) {
	typedResp := resp
	b.handler.updatePetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// RespondJSON404 sets the expectation to return a 404 response with JSON content.
func (b *UpdatePetExpectation) RespondJSON404(resp Error) {
	typedResp := UpdatePet404JSONResponse(resp)
	b.handler.updatePetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// RespondJSON422 sets the expectation to return a 422 response with JSON content.
func (b *UpdatePetExpectation) RespondJSON422(resp Error) {
	typedResp := UpdatePet422JSONResponse(resp)
	b.handler.updatePetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *UpdatePetExpectation) Handle(fn func(UpdatePetRequestObject, http.ResponseWriter) error) {
	resp := updatePetRawResponder{req: b.req, fn: fn}
	b.handler.updatePetExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

type FindPetsByStatusExpectation struct {
	handler *TestHandler
	req     FindPetsByStatusRequestObject
	opts    []ExpectOption
}

type findPetsByStatusRawResponder struct {
	req FindPetsByStatusRequestObject
	fn  func(FindPetsByStatusRequestObject, http.ResponseWriter) error
}

func (r findPetsByStatusRawResponder) VisitFindPetsByStatusResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *FindPetsByStatusExpectation) RespondJSON200(resp []Pet) {
	typedResp := FindPetsByStatus200JSONResponse(resp)
	b.handler.findPetsByStatusExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *FindPetsByStatusExpectation) Respond400() {
	var resp FindPetsByStatus400Response
	b.handler.findPetsByStatusExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *FindPetsByStatusExpectation) Handle(fn func(FindPetsByStatusRequestObject, http.ResponseWriter) error) {
	resp := findPetsByStatusRawResponder{req: b.req, fn: fn}
	b.handler.findPetsByStatusExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type FindPetsByTagsExpectation struct {
	handler *TestHandler
	req     FindPetsByTagsRequestObject
	opts    []ExpectOption
}

type findPetsByTagsRawResponder struct {
	req FindPetsByTagsRequestObject
	fn  func(FindPetsByTagsRequestObject, http.ResponseWriter) error
}

func (r findPetsByTagsRawResponder) VisitFindPetsByTagsResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *FindPetsByTagsExpectation) RespondJSON200(resp []Pet) {
	typedResp := FindPetsByTags200JSONResponse(resp)
	b.handler.findPetsByTagsExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *FindPetsByTagsExpectation) Respond400() {
	var resp FindPetsByTags400Response
	b.handler.findPetsByTagsExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *FindPetsByTagsExpectation) Handle(fn func(FindPetsByTagsRequestObject, http.ResponseWriter) error) {
	resp := findPetsByTagsRawResponder{req: b.req, fn: fn}
	b.handler.findPetsByTagsExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type DeletePetExpectation struct {
	handler *TestHandler
	req     DeletePetRequestObject
	opts    []ExpectOption
}

type deletePetRawResponder struct {
	req DeletePetRequestObject
	fn  func(DeletePetRequestObject, http.ResponseWriter) error
}

func (r deletePetRawResponder) VisitDeletePetResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *DeletePetExpectation) RespondJSON200(resp DeletePet200JSONResponse) {
	typedResp := resp
	b.handler.deletePetExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond204 sets the expectation to return a 204 response.
func (b *DeletePetExpectation) Respond204() {
	var resp DeletePet204Response
	b.handler.deletePetExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// RespondJSON400 sets the expectation to return a 400 response with JSON content.
func (b *DeletePetExpectation) RespondJSON400(resp DeletePet400JSONResponse) {
	typedResp := resp
	b.handler.deletePetExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// RespondJSON404 sets the expectation to return a 404 response with JSON content.
func (b *DeletePetExpectation) RespondJSON404(resp DeletePet404JSONResponse) {
	typedResp := resp
	b.handler.deletePetExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *DeletePetExpectation) Handle(fn func(DeletePetRequestObject, http.ResponseWriter) error) {
	resp := deletePetRawResponder{req: b.req, fn: fn}
	b.handler.deletePetExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type GetPetByIdExpectation struct {
	handler *TestHandler
	req     GetPetByIdRequestObject
	opts    []ExpectOption
}

type getPetByIdRawResponder struct {
	req GetPetByIdRequestObject
	fn  func(GetPetByIdRequestObject, http.ResponseWriter) error
}

func (r getPetByIdRawResponder) VisitGetPetByIdResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *GetPetByIdExpectation) RespondJSON200(resp Pet) {
	typedResp := GetPetById200JSONResponse(resp)
	b.handler.getPetByIdExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// RespondApplicationVndPetstorePlusJSON200 sets the expectation to return a 200 response with ApplicationVndPetstorePlusJSON content.
func (b *GetPetByIdExpectation) RespondApplicationVndPetstorePlusJSON200(resp Pet) {
	typedResp := GetPetById200ApplicationVndPetstorePlusJSONResponse(resp)
	b.handler.getPetByIdExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// RespondJSON400 sets the expectation to return a 400 response with JSON content.
func (b *GetPetByIdExpectation) RespondJSON400(resp GetPetById400JSONResponse) {
	typedResp := resp
	b.handler.getPetByIdExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// RespondJSON404 sets the expectation to return a 404 response with JSON content.
func (b *GetPetByIdExpectation) RespondJSON404(resp Error) {
	typedResp := GetPetById404JSONResponse(resp)
	b.handler.getPetByIdExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *GetPetByIdExpectation) Handle(fn func(GetPetByIdRequestObject, http.ResponseWriter) error) {
	resp := getPetByIdRawResponder{req: b.req, fn: fn}
	b.handler.getPetByIdExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type UpdatePetWithFormExpectation struct {
	handler *TestHandler
	req     UpdatePetWithFormRequestObject
	opts    []ExpectOption
}

type updatePetWithFormRawResponder struct {
	req UpdatePetWithFormRequestObject
	fn  func(UpdatePetWithFormRequestObject, http.ResponseWriter) error
}

func (r updatePetWithFormRawResponder) VisitUpdatePetWithFormResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *UpdatePetWithFormExpectation) RespondJSON200(resp Pet) {
	typedResp := UpdatePetWithForm200JSONResponse(resp)
	b.handler.updatePetWithFormExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *UpdatePetWithFormExpectation) Respond400() {
	var resp UpdatePetWithForm400Response
	b.handler.updatePetWithFormExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *UpdatePetWithFormExpectation) Handle(fn func(UpdatePetWithFormRequestObject, http.ResponseWriter) error) {
	resp := updatePetWithFormRawResponder{req: b.req, fn: fn}
	b.handler.updatePetWithFormExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type GetPetMetadataExpectation struct {
	handler *TestHandler
	req     GetPetMetadataRequestObject
	opts    []ExpectOption
}

type getPetMetadataRawResponder struct {
	req GetPetMetadataRequestObject
	fn  func(GetPetMetadataRequestObject, http.ResponseWriter) error
}

func (r getPetMetadataRawResponder) VisitGetPetMetadataResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *GetPetMetadataExpectation) RespondJSON200(resp map[string]string) {
	typedResp := GetPetMetadata200JSONResponse(resp)
	b.handler.getPetMetadataExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond204 sets the expectation to return a 204 response.
func (b *GetPetMetadataExpectation) Respond204() {
	var resp GetPetMetadata204Response
	b.handler.getPetMetadataExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// RespondJSON404 sets the expectation to return a 404 response with JSON content.
func (b *GetPetMetadataExpectation) RespondJSON404(resp GetPetMetadata404JSONResponse) {
	typedResp := resp
	b.handler.getPetMetadataExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *GetPetMetadataExpectation) Handle(fn func(GetPetMetadataRequestObject, http.ResponseWriter) error) {
	resp := getPetMetadataRawResponder{req: b.req, fn: fn}
	b.handler.getPetMetadataExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type GetPetPhotoByIdExpectation struct {
	handler *TestHandler
	req     GetPetPhotoByIdRequestObject
	opts    []ExpectOption
}

type getPetPhotoByIdRawResponder struct {
	req GetPetPhotoByIdRequestObject
	fn  func(GetPetPhotoByIdRequestObject, http.ResponseWriter) error
}

func (r getPetPhotoByIdRawResponder) VisitGetPetPhotoByIdResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *GetPetPhotoByIdExpectation) RespondJSON200(resp PetPhoto) {
	typedResp := GetPetPhotoById200JSONResponse(resp)
	b.handler.getPetPhotoByIdExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// RespondJSON404 sets the expectation to return a 404 response with JSON content.
func (b *GetPetPhotoByIdExpectation) RespondJSON404(resp GetPetPhotoById404JSONResponse) {
	typedResp := resp
	b.handler.getPetPhotoByIdExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *GetPetPhotoByIdExpectation) Handle(fn func(GetPetPhotoByIdRequestObject, http.ResponseWriter) error) {
	resp := getPetPhotoByIdRawResponder{req: b.req, fn: fn}
	b.handler.getPetPhotoByIdExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type GetPetRegistrationExpectation struct {
	handler *TestHandler
	req     GetPetRegistrationRequestObject
	opts    []ExpectOption
}

type getPetRegistrationRawResponder struct {
	req GetPetRegistrationRequestObject
	fn  func(GetPetRegistrationRequestObject, http.ResponseWriter) error
}

func (r getPetRegistrationRawResponder) VisitGetPetRegistrationResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *GetPetRegistrationExpectation) RespondJSON200(resp PetWithCustomTypes) {
	typedResp := GetPetRegistration200JSONResponse(resp)
	b.handler.getPetRegistrationExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// RespondJSON404 sets the expectation to return a 404 response with JSON content.
func (b *GetPetRegistrationExpectation) RespondJSON404(resp Error) {
	typedResp := GetPetRegistration404JSONResponse(resp)
	b.handler.getPetRegistrationExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *GetPetRegistrationExpectation) Handle(fn func(GetPetRegistrationRequestObject, http.ResponseWriter) error) {
	resp := getPetRegistrationRawResponder{req: b.req, fn: fn}
	b.handler.getPetRegistrationExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type UploadFileExpectation struct {
	handler *TestHandler
	req     UploadFileRequestObject
	rawBody io.Reader
	opts    []ExpectOption
}

type uploadFileRawResponder struct {
	req UploadFileRequestObject
	fn  func(UploadFileRequestObject, http.ResponseWriter) error
}

func (r uploadFileRawResponder) VisitUploadFileResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *UploadFileExpectation) RespondJSON200(resp ApiResponse) {
	typedResp := UploadFile200JSONResponse(resp)
	b.handler.uploadFileExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *UploadFileExpectation) Respond400() {
	var resp UploadFile400Response
	b.handler.uploadFileExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Respond404 sets the expectation to return a 404 response.
func (b *UploadFileExpectation) Respond404() {
	var resp UploadFile404Response
	b.handler.uploadFileExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *UploadFileExpectation) Handle(fn func(UploadFileRequestObject, http.ResponseWriter) error) {
	resp := uploadFileRawResponder{req: b.req, fn: fn}
	b.handler.uploadFileExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

type GetStoreInventoryExpectation struct {
	handler *TestHandler
	req     GetStoreInventoryRequestObject
	opts    []ExpectOption
}

type getStoreInventoryRawResponder struct {
	req GetStoreInventoryRequestObject
	fn  func(GetStoreInventoryRequestObject, http.ResponseWriter) error
}

func (r getStoreInventoryRawResponder) VisitGetStoreInventoryResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *GetStoreInventoryExpectation) RespondJSON200(resp map[string]int32) {
	typedResp := GetStoreInventory200JSONResponse(resp)
	b.handler.getStoreInventoryExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *GetStoreInventoryExpectation) Handle(fn func(GetStoreInventoryRequestObject, http.ResponseWriter) error) {
	resp := getStoreInventoryRawResponder{req: b.req, fn: fn}
	b.handler.getStoreInventoryExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type PostStoreOrderExpectation struct {
	handler *TestHandler
	req     PostStoreOrderRequestObject
	rawBody io.Reader
	opts    []ExpectOption
}

type postStoreOrderRawResponder struct {
	req PostStoreOrderRequestObject
	fn  func(PostStoreOrderRequestObject, http.ResponseWriter) error
}

func (r postStoreOrderRawResponder) VisitPostStoreOrderResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *PostStoreOrderExpectation) RespondJSON200(resp Order) {
	typedResp := PostStoreOrder200JSONResponse(resp)
	b.handler.postStoreOrderExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *PostStoreOrderExpectation) Respond400() {
	var resp PostStoreOrder400Response
	b.handler.postStoreOrderExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Respond422 sets the expectation to return a 422 response.
func (b *PostStoreOrderExpectation) Respond422() {
	var resp PostStoreOrder422Response
	b.handler.postStoreOrderExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *PostStoreOrderExpectation) Handle(fn func(PostStoreOrderRequestObject, http.ResponseWriter) error) {
	resp := postStoreOrderRawResponder{req: b.req, fn: fn}
	b.handler.postStoreOrderExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

type DeleteOrderExpectation struct {
	handler *TestHandler
	req     DeleteOrderRequestObject
	opts    []ExpectOption
}

type deleteOrderRawResponder struct {
	req DeleteOrderRequestObject
	fn  func(DeleteOrderRequestObject, http.ResponseWriter) error
}

func (r deleteOrderRawResponder) VisitDeleteOrderResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// Respond200 sets the expectation to return a 200 response.
func (b *DeleteOrderExpectation) Respond200() {
	var resp DeleteOrder200Response
	b.handler.deleteOrderExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *DeleteOrderExpectation) Respond400() {
	var resp DeleteOrder400Response
	b.handler.deleteOrderExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Respond404 sets the expectation to return a 404 response.
func (b *DeleteOrderExpectation) Respond404() {
	var resp DeleteOrder404Response
	b.handler.deleteOrderExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *DeleteOrderExpectation) Handle(fn func(DeleteOrderRequestObject, http.ResponseWriter) error) {
	resp := deleteOrderRawResponder{req: b.req, fn: fn}
	b.handler.deleteOrderExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type GetOrderByIdExpectation struct {
	handler *TestHandler
	req     GetOrderByIdRequestObject
	opts    []ExpectOption
}

type getOrderByIdRawResponder struct {
	req GetOrderByIdRequestObject
	fn  func(GetOrderByIdRequestObject, http.ResponseWriter) error
}

func (r getOrderByIdRawResponder) VisitGetOrderByIdResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *GetOrderByIdExpectation) RespondJSON200(resp Order) {
	typedResp := GetOrderById200JSONResponse(resp)
	b.handler.getOrderByIdExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *GetOrderByIdExpectation) Respond400() {
	var resp GetOrderById400Response
	b.handler.getOrderByIdExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Respond404 sets the expectation to return a 404 response.
func (b *GetOrderByIdExpectation) Respond404() {
	var resp GetOrderById404Response
	b.handler.getOrderByIdExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *GetOrderByIdExpectation) Handle(fn func(GetOrderByIdRequestObject, http.ResponseWriter) error) {
	resp := getOrderByIdRawResponder{req: b.req, fn: fn}
	b.handler.getOrderByIdExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type CreateUserExpectation struct {
	handler *TestHandler
	req     CreateUserRequestObject
	rawBody io.Reader
	opts    []ExpectOption
}

type createUserRawResponder struct {
	req CreateUserRequestObject
	fn  func(CreateUserRequestObject, http.ResponseWriter) error
}

func (r createUserRawResponder) VisitCreateUserResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *CreateUserExpectation) RespondJSON200(resp externalRef0.User) {
	typedResp := CreateUser200JSONResponse(resp)
	b.handler.createUserExpectResponses.expect(b.handler.tb, b.req, b.rawBody, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *CreateUserExpectation) Handle(fn func(CreateUserRequestObject, http.ResponseWriter) error) {
	resp := createUserRawResponder{req: b.req, fn: fn}
	b.handler.createUserExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

type CreateUsersWithListInputExpectation struct {
	handler *TestHandler
	req     CreateUsersWithListInputRequestObject
	opts    []ExpectOption
}

type createUsersWithListInputRawResponder struct {
	req CreateUsersWithListInputRequestObject
	fn  func(CreateUsersWithListInputRequestObject, http.ResponseWriter) error
}

func (r createUsersWithListInputRawResponder) VisitCreateUsersWithListInputResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *CreateUsersWithListInputExpectation) RespondJSON200(resp externalRef0.User) {
	typedResp := CreateUsersWithListInput200JSONResponse(resp)
	b.handler.createUsersWithListInputExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *CreateUsersWithListInputExpectation) Handle(fn func(CreateUsersWithListInputRequestObject, http.ResponseWriter) error) {
	resp := createUsersWithListInputRawResponder{req: b.req, fn: fn}
	b.handler.createUsersWithListInputExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type LoginUserExpectation struct {
	handler *TestHandler
	req     LoginUserRequestObject
	opts    []ExpectOption
}

type loginUserRawResponder struct {
	req LoginUserRequestObject
	fn  func(LoginUserRequestObject, http.ResponseWriter) error
}

func (r loginUserRawResponder) VisitLoginUserResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *LoginUserExpectation) RespondJSON200(resp LoginUser200JSONResponse) {
	typedResp := resp
	b.handler.loginUserExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *LoginUserExpectation) Respond400() {
	var resp LoginUser400Response
	b.handler.loginUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *LoginUserExpectation) Handle(fn func(LoginUserRequestObject, http.ResponseWriter) error) {
	resp := loginUserRawResponder{req: b.req, fn: fn}
	b.handler.loginUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type LogoutUserExpectation struct {
	handler *TestHandler
	req     LogoutUserRequestObject
	opts    []ExpectOption
}

type logoutUserRawResponder struct {
	req LogoutUserRequestObject
	fn  func(LogoutUserRequestObject, http.ResponseWriter) error
}

func (r logoutUserRawResponder) VisitLogoutUserResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// Respond200 sets the expectation to return a 200 response.
func (b *LogoutUserExpectation) Respond200() {
	var resp LogoutUser200Response
	b.handler.logoutUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *LogoutUserExpectation) Handle(fn func(LogoutUserRequestObject, http.ResponseWriter) error) {
	resp := logoutUserRawResponder{req: b.req, fn: fn}
	b.handler.logoutUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type DeleteUserExpectation struct {
	handler *TestHandler
	req     DeleteUserRequestObject
	opts    []ExpectOption
}

type deleteUserRawResponder struct {
	req DeleteUserRequestObject
	fn  func(DeleteUserRequestObject, http.ResponseWriter) error
}

func (r deleteUserRawResponder) VisitDeleteUserResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// Respond200 sets the expectation to return a 200 response.
func (b *DeleteUserExpectation) Respond200() {
	var resp DeleteUser200Response
	b.handler.deleteUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *DeleteUserExpectation) Respond400() {
	var resp DeleteUser400Response
	b.handler.deleteUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Respond404 sets the expectation to return a 404 response.
func (b *DeleteUserExpectation) Respond404() {
	var resp DeleteUser404Response
	b.handler.deleteUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *DeleteUserExpectation) Handle(fn func(DeleteUserRequestObject, http.ResponseWriter) error) {
	resp := deleteUserRawResponder{req: b.req, fn: fn}
	b.handler.deleteUserExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type GetUserByNameExpectation struct {
	handler *TestHandler
	req     GetUserByNameRequestObject
	opts    []ExpectOption
}

type getUserByNameRawResponder struct {
	req GetUserByNameRequestObject
	fn  func(GetUserByNameRequestObject, http.ResponseWriter) error
}

func (r getUserByNameRawResponder) VisitGetUserByNameResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// RespondJSON200 sets the expectation to return a 200 response with JSON content.
func (b *GetUserByNameExpectation) RespondJSON200(resp externalRef0.User) {
	typedResp := GetUserByName200JSONResponse(resp)
	b.handler.getUserByNameExpectResponses.expect(b.handler.tb, b.req, nil, typedResp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *GetUserByNameExpectation) Respond400() {
	var resp GetUserByName400Response
	b.handler.getUserByNameExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Respond404 sets the expectation to return a 404 response.
func (b *GetUserByNameExpectation) Respond404() {
	var resp GetUserByName404Response
	b.handler.getUserByNameExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *GetUserByNameExpectation) Handle(fn func(GetUserByNameRequestObject, http.ResponseWriter) error) {
	resp := getUserByNameRawResponder{req: b.req, fn: fn}
	b.handler.getUserByNameExpectResponses.expect(b.handler.tb, b.req, nil, resp, b.opts...)
}

type UpdateUserExpectation struct {
	handler *TestHandler
	req     UpdateUserRequestObject
	rawBody io.Reader
	opts    []ExpectOption
}

type updateUserRawResponder struct {
	req UpdateUserRequestObject
	fn  func(UpdateUserRequestObject, http.ResponseWriter) error
}

func (r updateUserRawResponder) VisitUpdateUserResponse(w http.ResponseWriter) error {
	return r.fn(r.req, w)
}

// Respond200 sets the expectation to return a 200 response.
func (b *UpdateUserExpectation) Respond200() {
	var resp UpdateUser200Response
	b.handler.updateUserExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Respond400 sets the expectation to return a 400 response.
func (b *UpdateUserExpectation) Respond400() {
	var resp UpdateUser400Response
	b.handler.updateUserExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Respond404 sets the expectation to return a 404 response.
func (b *UpdateUserExpectation) Respond404() {
	var resp UpdateUser404Response
	b.handler.updateUserExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function with full control over the HTTP response.
func (b *UpdateUserExpectation) Handle(fn func(UpdateUserRequestObject, http.ResponseWriter) error) {
	resp := updateUserRawResponder{req: b.req, fn: fn}
	b.handler.updateUserExpectResponses.expect(b.handler.tb, b.req, b.rawBody, resp, b.opts...)
}

func (s *TestHandler) ExpectAddPet(
	body AddPetJSONRequestBody,
	opts ...ExpectOption,
) *AddPetExpectation {
	req := AddPetRequestObject{
		JSONBody: &body,
	}
	return &AddPetExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectAddPetWithFormdataBody(
	body AddPetFormdataRequestBody,
	opts ...ExpectOption,
) *AddPetExpectation {
	req := AddPetRequestObject{
		FormdataBody: &body,
	}
	return &AddPetExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectAddPetWithBody(
	contentType string,
	body []byte,
	opts ...ExpectOption,
) *AddPetExpectation {
	req := AddPetRequestObject{
		Body: bytes.NewReader(body),
	}
	return &AddPetExpectation{
		handler: s,
		req:     req,
		rawBody: bytes.NewReader(body),
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUpdatePet(
	body UpdatePetJSONRequestBody,
	opts ...ExpectOption,
) *UpdatePetExpectation {
	req := UpdatePetRequestObject{
		JSONBody: &body,
	}
	return &UpdatePetExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUpdatePetWithFormdataBody(
	body UpdatePetFormdataRequestBody,
	opts ...ExpectOption,
) *UpdatePetExpectation {
	req := UpdatePetRequestObject{
		FormdataBody: &body,
	}
	return &UpdatePetExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUpdatePetWithBody(
	contentType string,
	body []byte,
	opts ...ExpectOption,
) *UpdatePetExpectation {
	req := UpdatePetRequestObject{
		Body: bytes.NewReader(body),
	}
	return &UpdatePetExpectation{
		handler: s,
		req:     req,
		rawBody: bytes.NewReader(body),
		opts:    opts,
	}
}

func (s *TestHandler) ExpectFindPetsByStatus(
	queryParams *FindPetsByStatusParams,
	opts ...ExpectOption,
) *FindPetsByStatusExpectation {
	req := FindPetsByStatusRequestObject{}
	if queryParams != nil {
		req.Params = *queryParams
	}
	return &FindPetsByStatusExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectFindPetsByTags(
	queryParams *FindPetsByTagsParams,
	opts ...ExpectOption,
) *FindPetsByTagsExpectation {
	req := FindPetsByTagsRequestObject{}
	if queryParams != nil {
		req.Params = *queryParams
	}
	return &FindPetsByTagsExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectDeletePet(
	petId int64,
	queryParams *DeletePetParams,
	opts ...ExpectOption,
) *DeletePetExpectation {
	req := DeletePetRequestObject{
		PetId: petId,
	}
	if queryParams != nil {
		req.Params = *queryParams
	}
	return &DeletePetExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectGetPetById(
	petId int64,
	opts ...ExpectOption,
) *GetPetByIdExpectation {
	req := GetPetByIdRequestObject{
		PetId: petId,
	}
	return &GetPetByIdExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUpdatePetWithForm(
	petId int64,
	queryParams *UpdatePetWithFormParams,
	opts ...ExpectOption,
) *UpdatePetWithFormExpectation {
	req := UpdatePetWithFormRequestObject{
		PetId: petId,
	}
	if queryParams != nil {
		req.Params = *queryParams
	}
	return &UpdatePetWithFormExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectGetPetMetadata(
	petId int64,
	queryParams *GetPetMetadataParams,
	opts ...ExpectOption,
) *GetPetMetadataExpectation {
	req := GetPetMetadataRequestObject{
		PetId: petId,
	}
	if queryParams != nil {
		req.Params = *queryParams
	}
	return &GetPetMetadataExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectGetPetPhotoById(
	petId int64,
	photoId int64,
	opts ...ExpectOption,
) *GetPetPhotoByIdExpectation {
	req := GetPetPhotoByIdRequestObject{
		PetId:   petId,
		PhotoId: photoId,
	}
	return &GetPetPhotoByIdExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectGetPetRegistration(
	petId int64,
	opts ...ExpectOption,
) *GetPetRegistrationExpectation {
	req := GetPetRegistrationRequestObject{
		PetId: petId,
	}
	return &GetPetRegistrationExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUploadFileWithBody(
	petId int64,
	contentType string,
	body []byte,
	opts ...ExpectOption,
) *UploadFileExpectation {
	req := UploadFileRequestObject{
		PetId: petId,
		Body:  bytes.NewReader(body),
	}
	return &UploadFileExpectation{
		handler: s,
		req:     req,
		rawBody: bytes.NewReader(body),
		opts:    opts,
	}
}

func (s *TestHandler) ExpectGetStoreInventory(
	opts ...ExpectOption,
) *GetStoreInventoryExpectation {
	req := GetStoreInventoryRequestObject{}
	return &GetStoreInventoryExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectPostStoreOrder(
	body PostStoreOrderJSONRequestBody,
	opts ...ExpectOption,
) *PostStoreOrderExpectation {
	req := PostStoreOrderRequestObject{
		JSONBody: &body,
	}
	return &PostStoreOrderExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectPostStoreOrderWithFormdataBody(
	body PostStoreOrderFormdataRequestBody,
	opts ...ExpectOption,
) *PostStoreOrderExpectation {
	req := PostStoreOrderRequestObject{
		FormdataBody: &body,
	}
	return &PostStoreOrderExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectPostStoreOrderWithBody(
	contentType string,
	body []byte,
	opts ...ExpectOption,
) *PostStoreOrderExpectation {
	req := PostStoreOrderRequestObject{
		Body: bytes.NewReader(body),
	}
	return &PostStoreOrderExpectation{
		handler: s,
		req:     req,
		rawBody: bytes.NewReader(body),
		opts:    opts,
	}
}

func (s *TestHandler) ExpectDeleteOrder(
	orderId int64,
	opts ...ExpectOption,
) *DeleteOrderExpectation {
	req := DeleteOrderRequestObject{
		OrderId: orderId,
	}
	return &DeleteOrderExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectGetOrderById(
	orderId int64,
	opts ...ExpectOption,
) *GetOrderByIdExpectation {
	req := GetOrderByIdRequestObject{
		OrderId: orderId,
	}
	return &GetOrderByIdExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectCreateUser(
	body CreateUserJSONRequestBody,
	opts ...ExpectOption,
) *CreateUserExpectation {
	req := CreateUserRequestObject{
		JSONBody: &body,
	}
	return &CreateUserExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectCreateUserWithFormdataBody(
	body CreateUserFormdataRequestBody,
	opts ...ExpectOption,
) *CreateUserExpectation {
	req := CreateUserRequestObject{
		FormdataBody: &body,
	}
	return &CreateUserExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectCreateUserWithBody(
	contentType string,
	body []byte,
	opts ...ExpectOption,
) *CreateUserExpectation {
	req := CreateUserRequestObject{
		Body: bytes.NewReader(body),
	}
	return &CreateUserExpectation{
		handler: s,
		req:     req,
		rawBody: bytes.NewReader(body),
		opts:    opts,
	}
}

func (s *TestHandler) ExpectCreateUsersWithListInput(
	body CreateUsersWithListInputJSONRequestBody,
	opts ...ExpectOption,
) *CreateUsersWithListInputExpectation {
	req := CreateUsersWithListInputRequestObject{
		Body: &body,
	}
	return &CreateUsersWithListInputExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectLoginUser(
	queryParams *LoginUserParams,
	opts ...ExpectOption,
) *LoginUserExpectation {
	req := LoginUserRequestObject{}
	if queryParams != nil {
		req.Params = *queryParams
	}
	return &LoginUserExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectLogoutUser(
	opts ...ExpectOption,
) *LogoutUserExpectation {
	req := LogoutUserRequestObject{}
	return &LogoutUserExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectDeleteUser(
	username string,
	opts ...ExpectOption,
) *DeleteUserExpectation {
	req := DeleteUserRequestObject{
		Username: username,
	}
	return &DeleteUserExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectGetUserByName(
	username string,
	opts ...ExpectOption,
) *GetUserByNameExpectation {
	req := GetUserByNameRequestObject{
		Username: username,
	}
	return &GetUserByNameExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUpdateUser(
	username string,
	body UpdateUserJSONRequestBody,
	opts ...ExpectOption,
) *UpdateUserExpectation {
	req := UpdateUserRequestObject{
		Username: username,
		JSONBody: &body,
	}
	return &UpdateUserExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUpdateUserWithFormdataBody(
	username string,
	body UpdateUserFormdataRequestBody,
	opts ...ExpectOption,
) *UpdateUserExpectation {
	req := UpdateUserRequestObject{
		Username:     username,
		FormdataBody: &body,
	}
	return &UpdateUserExpectation{
		handler: s,
		req:     req,
		opts:    opts,
	}
}

func (s *TestHandler) ExpectUpdateUserWithBody(
	username string,
	contentType string,
	body []byte,
	opts ...ExpectOption,
) *UpdateUserExpectation {
	req := UpdateUserRequestObject{
		Username: username,
		Body:     bytes.NewReader(body),
	}
	return &UpdateUserExpectation{
		handler: s,
		req:     req,
		rawBody: bytes.NewReader(body),
		opts:    opts,
	}
}
