// Code generated by github.com/willabides/oapitesthandler/cmd/oapitesthandler. DO NOT EDIT.

package petstoretest

import (
	"net/http"
)

type TestHandler struct {
	tb TB

	handler http.Handler

	addPetExpectations                   expectations[AddPetRequestObject, AddPetResponseObject]
	updatePetExpectations                expectations[UpdatePetRequestObject, UpdatePetResponseObject]
	findPetsByStatusExpectations         expectations[FindPetsByStatusRequestObject, FindPetsByStatusResponseObject]
	findPetsByTagsExpectations           expectations[FindPetsByTagsRequestObject, FindPetsByTagsResponseObject]
	deletePetExpectations                expectations[DeletePetRequestObject, DeletePetResponseObject]
	getPetByIdExpectations               expectations[GetPetByIdRequestObject, GetPetByIdResponseObject]
	updatePetWithFormExpectations        expectations[UpdatePetWithFormRequestObject, UpdatePetWithFormResponseObject]
	getPetMetadataExpectations           expectations[GetPetMetadataRequestObject, GetPetMetadataResponseObject]
	getPetPhotoByIdExpectations          expectations[GetPetPhotoByIdRequestObject, GetPetPhotoByIdResponseObject]
	getPetRegistrationExpectations       expectations[GetPetRegistrationRequestObject, GetPetRegistrationResponseObject]
	uploadFileExpectations               expectations[UploadFileRequestObject, UploadFileResponseObject]
	getStoreInventoryExpectations        expectations[GetStoreInventoryRequestObject, GetStoreInventoryResponseObject]
	postStoreOrderExpectations           expectations[PostStoreOrderRequestObject, PostStoreOrderResponseObject]
	deleteOrderExpectations              expectations[DeleteOrderRequestObject, DeleteOrderResponseObject]
	getOrderByIdExpectations             expectations[GetOrderByIdRequestObject, GetOrderByIdResponseObject]
	createUserExpectations               expectations[CreateUserRequestObject, CreateUserResponseObject]
	createUsersWithListInputExpectations expectations[CreateUsersWithListInputRequestObject, CreateUsersWithListInputResponseObject]
	loginUserExpectations                expectations[LoginUserRequestObject, LoginUserResponseObject]
	logoutUserExpectations               expectations[LogoutUserRequestObject, LogoutUserResponseObject]
	deleteUserExpectations               expectations[DeleteUserRequestObject, DeleteUserResponseObject]
	getUserByNameExpectations            expectations[GetUserByNameRequestObject, GetUserByNameResponseObject]
	updateUserExpectations               expectations[UpdateUserRequestObject, UpdateUserResponseObject]
}

func (s *TestHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.handler.ServeHTTP(w, r)
}

func NewTestHandler(tb TB) *TestHandler {
	th := &TestHandler{tb: tb}
	s := &testServer{tb: tb, handler: th}
	th.handler = Handler(NewStrictHandler(s, nil))
	return th
}

func (s *TestHandler) ExpectAddPet(
	req AddPetRequestObject,
	resp AddPetResponseObject,
	opts ...ExpectOption,
) {
	s.addPetExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectUpdatePet(
	req UpdatePetRequestObject,
	resp UpdatePetResponseObject,
	opts ...ExpectOption,
) {
	s.updatePetExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectFindPetsByStatus(
	req FindPetsByStatusRequestObject,
	resp FindPetsByStatusResponseObject,
	opts ...ExpectOption,
) {
	s.findPetsByStatusExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectFindPetsByTags(
	req FindPetsByTagsRequestObject,
	resp FindPetsByTagsResponseObject,
	opts ...ExpectOption,
) {
	s.findPetsByTagsExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectDeletePet(
	req DeletePetRequestObject,
	resp DeletePetResponseObject,
	opts ...ExpectOption,
) {
	s.deletePetExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectGetPetById(
	req GetPetByIdRequestObject,
	resp GetPetByIdResponseObject,
	opts ...ExpectOption,
) {
	s.getPetByIdExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectUpdatePetWithForm(
	req UpdatePetWithFormRequestObject,
	resp UpdatePetWithFormResponseObject,
	opts ...ExpectOption,
) {
	s.updatePetWithFormExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectGetPetMetadata(
	req GetPetMetadataRequestObject,
	resp GetPetMetadataResponseObject,
	opts ...ExpectOption,
) {
	s.getPetMetadataExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectGetPetPhotoById(
	req GetPetPhotoByIdRequestObject,
	resp GetPetPhotoByIdResponseObject,
	opts ...ExpectOption,
) {
	s.getPetPhotoByIdExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectGetPetRegistration(
	req GetPetRegistrationRequestObject,
	resp GetPetRegistrationResponseObject,
	opts ...ExpectOption,
) {
	s.getPetRegistrationExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectUploadFile(
	req UploadFileRequestObject,
	resp UploadFileResponseObject,
	opts ...ExpectOption,
) {
	s.uploadFileExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectGetStoreInventory(
	req GetStoreInventoryRequestObject,
	resp GetStoreInventoryResponseObject,
	opts ...ExpectOption,
) {
	s.getStoreInventoryExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectPostStoreOrder(
	req PostStoreOrderRequestObject,
	resp PostStoreOrderResponseObject,
	opts ...ExpectOption,
) {
	s.postStoreOrderExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectDeleteOrder(
	req DeleteOrderRequestObject,
	resp DeleteOrderResponseObject,
	opts ...ExpectOption,
) {
	s.deleteOrderExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectGetOrderById(
	req GetOrderByIdRequestObject,
	resp GetOrderByIdResponseObject,
	opts ...ExpectOption,
) {
	s.getOrderByIdExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectCreateUser(
	req CreateUserRequestObject,
	resp CreateUserResponseObject,
	opts ...ExpectOption,
) {
	s.createUserExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectCreateUsersWithListInput(
	req CreateUsersWithListInputRequestObject,
	resp CreateUsersWithListInputResponseObject,
	opts ...ExpectOption,
) {
	s.createUsersWithListInputExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectLoginUser(
	req LoginUserRequestObject,
	resp LoginUserResponseObject,
	opts ...ExpectOption,
) {
	s.loginUserExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectLogoutUser(
	req LogoutUserRequestObject,
	resp LogoutUserResponseObject,
	opts ...ExpectOption,
) {
	s.logoutUserExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectDeleteUser(
	req DeleteUserRequestObject,
	resp DeleteUserResponseObject,
	opts ...ExpectOption,
) {
	s.deleteUserExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectGetUserByName(
	req GetUserByNameRequestObject,
	resp GetUserByNameResponseObject,
	opts ...ExpectOption,
) {
	s.getUserByNameExpectations.Expect(s.tb, req, resp, opts...)
}

func (s *TestHandler) ExpectUpdateUser(
	req UpdateUserRequestObject,
	resp UpdateUserResponseObject,
	opts ...ExpectOption,
) {
	s.updateUserExpectations.Expect(s.tb, req, resp, opts...)
}
