// Code generated by github.com/willabides/oapitesthandler/cmd/oapitesthandler. DO NOT EDIT.

package petstoretest

import (
	clientpkg "github.com/willabides/oapitesthandler/example/petstore/internal/oapi"
)

const (
	Api_keyScopes       = clientpkg.Api_keyScopes
	Petstore_authScopes = clientpkg.Petstore_authScopes
)

const (
	OrderStatusApproved  = clientpkg.OrderStatusApproved
	OrderStatusDelivered = clientpkg.OrderStatusDelivered
	OrderStatusPlaced    = clientpkg.OrderStatusPlaced
)

const (
	PetStatusAvailable = clientpkg.PetStatusAvailable
	PetStatusPending   = clientpkg.PetStatusPending
	PetStatusSold      = clientpkg.PetStatusSold
)

const (
	FindPetsByStatusParamsStatusAvailable = clientpkg.FindPetsByStatusParamsStatusAvailable
	FindPetsByStatusParamsStatusPending   = clientpkg.FindPetsByStatusParamsStatusPending
	FindPetsByStatusParamsStatusSold      = clientpkg.FindPetsByStatusParamsStatusSold
)

type ApiResponse = clientpkg.ApiResponse

type BasePhoto = clientpkg.BasePhoto

type Category = clientpkg.Category

type Order = clientpkg.Order

type OrderStatus = clientpkg.OrderStatus

type Pet = clientpkg.Pet

type PetStatus = clientpkg.PetStatus

type PetPhoto = clientpkg.PetPhoto

type PetWithCustomTypes = clientpkg.PetWithCustomTypes

type Tag = clientpkg.Tag

type Timestamp = clientpkg.Timestamp

type UUID = clientpkg.UUID

type Error = clientpkg.Error

type FindPetsByStatusParams = clientpkg.FindPetsByStatusParams

type FindPetsByStatusParamsStatus = clientpkg.FindPetsByStatusParamsStatus

type FindPetsByTagsParams = clientpkg.FindPetsByTagsParams

type DeletePetParams = clientpkg.DeletePetParams

type UpdatePetWithFormParams = clientpkg.UpdatePetWithFormParams

type GetPetMetadataParams = clientpkg.GetPetMetadataParams

type UploadFileParams = clientpkg.UploadFileParams

type CreateUsersWithListInputJSONBody = clientpkg.CreateUsersWithListInputJSONBody

type LoginUserParams = clientpkg.LoginUserParams

type AddPetJSONRequestBody = clientpkg.AddPetJSONRequestBody

type AddPetFormdataRequestBody = clientpkg.AddPetFormdataRequestBody

type UpdatePetJSONRequestBody = clientpkg.UpdatePetJSONRequestBody

type UpdatePetFormdataRequestBody = clientpkg.UpdatePetFormdataRequestBody

type PostStoreOrderJSONRequestBody = clientpkg.PostStoreOrderJSONRequestBody

type PostStoreOrderFormdataRequestBody = clientpkg.PostStoreOrderFormdataRequestBody

type CreateUserJSONRequestBody = clientpkg.CreateUserJSONRequestBody

type CreateUserFormdataRequestBody = clientpkg.CreateUserFormdataRequestBody

type CreateUsersWithListInputJSONRequestBody = clientpkg.CreateUsersWithListInputJSONRequestBody

type UpdateUserJSONRequestBody = clientpkg.UpdateUserJSONRequestBody

type UpdateUserFormdataRequestBody = clientpkg.UpdateUserFormdataRequestBody
