// Package petstoretest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/willabides/oapitesthandler version (devel) DO NOT EDIT.
package petstoretest

import (
	externalRef0 "github.com/willabides/oapitesthandler/example/petstore/internal/common/oapi"
	modelspkg "github.com/willabides/oapitesthandler/example/petstore/internal/oapi"
)

const (
	Api_keyScopes       = modelspkg.Api_keyScopes
	Petstore_authScopes = modelspkg.Petstore_authScopes
)

type (
	ApiResponse        = modelspkg.ApiResponse
	BasePhoto          = modelspkg.BasePhoto
	Category           = modelspkg.Category
	Order              = modelspkg.Order
	OrderStatus        = modelspkg.OrderStatus
	Pet                = modelspkg.Pet
	PetStatus          = modelspkg.PetStatus
	PetPhoto           = modelspkg.PetPhoto
	PetWithCustomTypes = modelspkg.PetWithCustomTypes
	Tag                = modelspkg.Tag
	Timestamp          = modelspkg.Timestamp
	UUID               = modelspkg.UUID
	Error              = modelspkg.Error
)
type (
	FindPetsByStatusParams = modelspkg.FindPetsByStatusParams

	FindPetsByStatusParamsStatus = modelspkg.FindPetsByStatusParamsStatus

	FindPetsByTagsParams = modelspkg.FindPetsByTagsParams

	DeletePetParams = modelspkg.DeletePetParams

	UpdatePetWithFormParams = modelspkg.UpdatePetWithFormParams

	GetPetMetadataParams = modelspkg.GetPetMetadataParams

	UploadFileParams = modelspkg.UploadFileParams

	CreateUsersWithListInputJSONBody = modelspkg.CreateUsersWithListInputJSONBody

	LoginUserParams = modelspkg.LoginUserParams
)

// AddPetJSONRequestBody defines body for AddPet for application/json ContentType.
type AddPetJSONRequestBody = Pet

// AddPetFormdataRequestBody defines body for AddPet for application/x-www-form-urlencoded ContentType.
type AddPetFormdataRequestBody = Pet

// UpdatePetJSONRequestBody defines body for UpdatePet for application/json ContentType.
type UpdatePetJSONRequestBody = Pet

// UpdatePetFormdataRequestBody defines body for UpdatePet for application/x-www-form-urlencoded ContentType.
type UpdatePetFormdataRequestBody = Pet

// PostStoreOrderJSONRequestBody defines body for PostStoreOrder for application/json ContentType.
type PostStoreOrderJSONRequestBody = Order

// PostStoreOrderFormdataRequestBody defines body for PostStoreOrder for application/x-www-form-urlencoded ContentType.
type PostStoreOrderFormdataRequestBody = Order

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = externalRef0.User

// CreateUserFormdataRequestBody defines body for CreateUser for application/x-www-form-urlencoded ContentType.
type CreateUserFormdataRequestBody = externalRef0.User

// CreateUsersWithListInputJSONRequestBody defines body for CreateUsersWithListInput for application/json ContentType.
type CreateUsersWithListInputJSONRequestBody = CreateUsersWithListInputJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = externalRef0.User

// UpdateUserFormdataRequestBody defines body for UpdateUser for application/x-www-form-urlencoded ContentType.
type UpdateUserFormdataRequestBody = externalRef0.User
