# $schema: https://raw.githubusercontent.com/OAI/Overlay-Specification/refs/heads/main/schemas/v1.0/schema.yaml
overlay: 1.0.0
info:
  title: petstore fixes
  version: 1.0.0
actions:
  - target: "$"
    update:
      components:
        schemas:
          Pet:
            properties:
              id:
                type: integer
                format: int32
