#!/bin/sh
#/ script/oapitesthandler builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/oapitesthandler ./cmd/oapitesthandler

exec bin/oapitesthandler "$@"
